name: On issue label

on:
  issues:
    types: [labeled]

jobs:
  issue-on-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/issue-on-label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
